[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"


[functions]
	directory = "functions"
  external_node_modules = ["@netlify/functions"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"